services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - PROXY_LIST_URL=${PROXY_LIST_URL}
      - SCHEDULE_TIME=${SCHEDULE_TIME}

